In [2]:
from google.colab import files
file=files.upload()

Saving startup_funding.csv to startup_funding.csv

In [3]:
import pandas as pd

df = pd.read_csv("startup_funding.csv")
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [6]:
df.columns

Index(['Sr No', 'Date dd/mm/yyyy', 'Startup Name', 'Industry Vertical',
       'SubVertical', 'City  Location', 'Investors Name', 'InvestmentnType',
       'Amount in USD', 'Remarks'],
      dtype='object')

In [11]:
# Triming the Colums Names
df.columns = df.columns.str.strip()          # remove extra spaces at start/end
df.columns = df.columns.str.replace('  ', ' ')  # replace double spaces
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.lower()

print(df.columns)

Index(['sr_no', 'date_dd/mm/yyyy', 'startup_name', 'industry_vertical',
       'subvertical', 'city_location', 'investors_name', 'investmentntype',
       'amount_in_usd', 'remarks'],
      dtype='object')

In [25]:
#Check Missing Values
df.isnull().sum()

sr_no                   0
date_dd/mm/yyyy      1752
startup_name            0
industry_vertical       0
subvertical           936
city_location           0
investors_name          0
investmentntype         4
amount_in_usd           0
remarks              2625
year                 1752
funding_category        0
dtype: int64

In [13]:
# Handle missing values
df['industry_vertical'] = df['industry_vertical'].fillna("Unknown")
df['city_location'] = df['city_location'].fillna("Unknown")
df['investors_name'] = df['investors_name'].fillna("Undisclosed")

# Convert amount column
df['amount_in_usd'] = pd.to_numeric(df['amount_in_usd'], errors='coerce')
df['amount_in_usd'] = df['amount_in_usd'].fillna(df['amount_in_usd'].median())

In [14]:
#Remove Duplicate
df.drop_duplicates(inplace=True)

In [16]:
#Clean Text Columns
df['startup_name'] = df['startup_name'].str.strip().str.title()
df['city_location'] = df['city_location'].str.strip().str.title()
df['industry_vertical'] = df['industry_vertical'].str.strip().str.title()
df['investors_name'] = df['investors_name'].str.strip()

In [19]:
#Fix Date & Year
df['date_dd/mm/yyyy'] = pd.to_datetime(df['date_dd/mm/yyyy'], errors='coerce')
df['year'] = df['date_dd/mm/yyyy'].dt.year

In [20]:
#Create New Column
df['funding_category'] = df['amount_in_usd'].apply(lambda x:
    'Low' if x < 1000000 else
    'Medium' if x < 10000000 else
    'High'
)

In [24]:
#cleaned_dataset
df.to_csv("cleaned_dataset.csv", index=False)

In [23]:
#Downloading Cleaned data
from google.colab import files
files.download("cleaned_dataset.csv")